//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Text.JsonLab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStrings2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Text.JsonLab.ExceptionStrings2", typeof(ExceptionStrings2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentDepth ({0}) is larger than the maximum configured depth of {1}. Cannot read next JSON array..
        /// </summary>
        internal static string ArrayDepthTooLarge {
            get {
                return ResourceManager.GetString("ArrayDepthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of comment, but instead reached end of data..
        /// </summary>
        internal static string EndOfCommentNotFound {
            get {
                return ResourceManager.GetString("EndOfCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of string, but instead reached end of data..
        /// </summary>
        internal static string EndOfStringNotFound {
            get {
                return ResourceManager.GetString("EndOfStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a single JSON value. Expected end of data..
        /// </summary>
        internal static string ExpectedEndAfterSingleJson {
            get {
                return ResourceManager.GetString("ExpectedEndAfterSingleJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid end of a number. Expected a delimiter..
        /// </summary>
        internal static string ExpectedEndOfDigitNotFound {
            get {
                return ResourceManager.GetString("ExpectedEndOfDigitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;false&apos;..
        /// </summary>
        internal static string ExpectedFalse {
            get {
                return ResourceManager.GetString("ExpectedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid end of a number. Expected &apos;E&apos; or &apos;e&apos;..
        /// </summary>
        internal static string ExpectedNextDigitEValueNotFound {
            get {
                return ResourceManager.GetString("ExpectedNextDigitEValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;null&apos;..
        /// </summary>
        internal static string ExpectedNull {
            get {
                return ResourceManager.GetString("ExpectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a property name. Expected a &apos;:&apos;..
        /// </summary>
        internal static string ExpectedSeparatorAfterPropertyNameNotFound {
            get {
                return ResourceManager.GetString("ExpectedSeparatorAfterPropertyNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid start of a property name. Expected a &apos;&quot;&apos;..
        /// </summary>
        internal static string ExpectedStartOfPropertyNotFound {
            get {
                return ResourceManager.GetString("ExpectedStartOfPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected start of a property name or value, but instead reached end of data..
        /// </summary>
        internal static string ExpectedStartOfPropertyOrValueNotFound {
            get {
                return ResourceManager.GetString("ExpectedStartOfPropertyOrValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid start of a value..
        /// </summary>
        internal static string ExpectedStartOfValueNotFound {
            get {
                return ResourceManager.GetString("ExpectedStartOfValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid JSON literal. Expected the literal &apos;true&apos;..
        /// </summary>
        internal static string ExpectedTrue {
            get {
                return ResourceManager.GetString("ExpectedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a value, but instead reached end of data..
        /// </summary>
        internal static string ExpectedValueAfterPropertyNameNotFound {
            get {
                return ResourceManager.GetString("ExpectedValueAfterPropertyNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid after a value. Expected either &apos;,&apos;, &apos;}}&apos;, or &apos;]&apos;..
        /// </summary>
        internal static string FoundInvalidCharacter {
            get {
                return ResourceManager.GetString("FoundInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of a token type &apos;{0}&apos; as a {1}..
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a JSON string. The string should be correctly escaped..
        /// </summary>
        internal static string InvalidCharacterWithinString {
            get {
                return ResourceManager.GetString("InvalidCharacterWithinString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid token type for the end of the JSON payload. Expected either &apos;EndArray&apos; or &apos;EndObject&apos;..
        /// </summary>
        internal static string InvalidEndOfJsonNonPrimitive {
            get {
                return ResourceManager.GetString("InvalidEndOfJsonNonPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth must be positive..
        /// </summary>
        internal static string MaxDepthMustBePositive {
            get {
                return ResourceManager.GetString("MaxDepthMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid without a matching open..
        /// </summary>
        internal static string MismatchedObjectArray {
            get {
                return ResourceManager.GetString("MismatchedObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentDepth ({0}) is larger than the maximum configured depth of {1}. Cannot read next JSON object..
        /// </summary>
        internal static string ObjectDepthTooLarge {
            get {
                return ResourceManager.GetString("ObjectDepthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a number immediately after a decimal point (&apos;.&apos;). Expected a digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string RequiredDigitNotFoundAfterDecimal {
            get {
                return ResourceManager.GetString("RequiredDigitNotFoundAfterDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid within a number immediately after a sign character (&apos;+&apos; or &apos;-&apos;). Expected a digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string RequiredDigitNotFoundAfterSign {
            get {
                return ResourceManager.GetString("RequiredDigitNotFoundAfterSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a digit (&apos;0&apos;-&apos;9&apos;), but instead reached end of data..
        /// </summary>
        internal static string RequiredDigitNotFoundEndOfData {
            get {
                return ResourceManager.GetString("RequiredDigitNotFoundEndOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected CurrentDepth ({0}) to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed..
        /// </summary>
        internal static string ZeroDepthAtEnd {
            get {
                return ResourceManager.GetString("ZeroDepthAtEnd", resourceCulture);
            }
        }
    }
}
